posters:
 - title: "Discussing Early Phase Trials: Evaluation of a Cancer Research UK Educational Training Program"
   file: 110523_ASCOposter.pdf
   image: 110523_ASCOposter.jpg
   authors: Ivonne Solis-Trapala

 - title: "Geospatial Modelling of the Effect of Malrai Height of Children 0-5 in Africa"
   file: conference_poster_benjamin_amoah.pdf
   image: conference_poster_benjamin_amoah.jpg
   authors: Benjamin Amoah

 - title: "Adaptive Geostatistical Design and Analysis for Prevalence Surveys"
   file: Chipeta_FHM_poster.pdf
   image: Chipeta_FHM_poster.jpg
   authors: Michael Chipeta

 - title: "Bayesian Parameter Estimation for the log-Gaussian Cox Process"
   file: INFER2011.pdf
   image: INFER2011.jpg
   authors: Peter Diggle, Ben Taylor, Barry Rowlingson

 - title: "Understanding the Natural Progression in %FEV1 Decline in Patients with Cystic Fibrosis"
   file: ECFposter26May.pdf
   image: ECFposter26May.jpg
   authors: Peter Diggle

 - title: "Acute Response to Sarin in Veterans Tested at Porton Down"
   file: ISEE2009.pptx
   image: ISEE2009.jpg
   authors: Tom Keegan
 - title: "Survival and Serious Long Term Peritoneal Complications in Peritoneal Dialysis Patients"
   file: peritoneal_dialysis.ppt
   image: peritoneal_dialysis.jpg
   authors: Peter Diggle
 - title: "A Comparison of INLA and MCMC for the Estimation of Smoothed Risk Maps in Epidemiology"
   file: Ramis_poster_Zurich.pptx
   image: Ramis.jpg
   authors: Rebeca Ramis, Peter Diggle
 - title: "Relative Deprivation Between Neighbouring wards is Predictive of Coronary Heart Disease Mortality After Adjustment for Absolute Deprivation of Wards"
   file: deprivation.pptx
   image: deprivation.jpg
   authors: Tom Keegan
 - title: "Exploratory Analysis of Leptospirosis Cohort Data"
   file: leptospirosis.pdf
   image: leptospirosis.jpg
   authors: Nicolas Capian, Peter Diggle
 - title: "Omissions and Misunderstandings in Phase 1 Trial Discussions"
   file: 101013_FINALPhaseI.pdf
   image: 101013_FINALPhaseI.jpg
   authors: Ivonne Solis-Trapala
 - title: "Assessing Variability in Histological Grade of Breast Cancer Tumours"
   file: variability_breast_cancer_tumors.pdf
   image: variability_breast_cancer_tumors.jpg
   authors: Tom Fanshawe
 - title: "Towards Real-time Spatiotemporal Monitoring and Forecasting of Meningitis Incidence in sub-Saharan Africa"
   file: MERIT2010_poster_LA.MS.pdf
   image: MERIT2010.jpg
   authors: Michelle Stanton, Lydiane Agier, Barry Rowlingson, Peter Diggle
 - title: "A Study of Association of Workload with Infection of Ventilator-assisted Pneumonia on the Intensive Care Unit"
   file: VAPposter.pdf
   image: VAPposter.jpg
   authors: Lisha Deng, Peter Diggle
 - title: "Epidemiology of Meningococcal Meningitis in Niger : a District-based Comparative Study"
   file: meningitis_district_based_study.pdf
   image: meningitis_district_based_study.jpg
   authors: Lydiane Agier
 - title: "UK Oncologists' Experiences with and Attitudes Towards non-NHS-funded Cancer Drugs: Results from an On-line Survey"
   file: 101013_FINALDoH.pdf
   image: 101013_FINALDoH.jpg
   authors: Ivonne Solis-Trapala
 - title: "Preterm Birth in Liverpool: What is the Effect of Socio-economic Status? "
   file: preterm_birth.pdf
   image: preterm_birth.jpg
   authors: Peter Diggle
 - title: "Statistical Modelling of Development of Executive Function in Early Childhood"
   file: development_of_executive_function.pdf
   image: development_of_executive_function.jpg
   authors: Ivonne Solis-Trapala, Peter Diggle
 - title: "Modelling Malaria with Spatial Statistics and Satellite Data"
   file: modelling_malaria.pdf
   image: modelling_malaria.jpg
   authors: Barry Rowlingson, Peter Diggle
 - title: "Partial Likelihood Analysis for Spatio-temporal Point Process Data"
   file: point_processes.pdf
   image: point_processes.jpg
   authors: Irene Kaimi, Peter Diggle
 - title: "Modelling Spatio-temporal Variation in Black Smoke Pollutant Concentrations"
   file: modelling_spatio-temporal_variation.pdf
   image: modelling_spatio-temporal_variation.jpg
   authors: Tom Fanshawe, Peter Diggle
 - title: "The Use of Estimated Glomerular Filtration Rate and Albumin Creatinine Ratio to Predict Decline in Renal Function in People with Diabetes"
   file: decline_in_renal_function.pdf
   image: decline_in_renal_function.jpg
   authors: In&#234;s Sousa, Peter Diggle
 - title: "Microalbuminuria and Reduced Glomerular Filtration Rate are Independent Factors for Mortality in People with Diabetes Mellitus"
   file: diabetes_mellitus.pdf
   image: diabetes_mellitus.jpg
   authors: In&#234;s Sousa, Peter Diggle
 - title: "Effect of Socio-economic Status on Lung Function in the UK Cystic Fibrosis Population"
   file: NACFposter6Oct.pdf
   image: NACF.jpg
   authors: Peter Diggle
 - title: "Real-time Spatio-temporal Surveillance: the AEGISS Project"
   file: AEGISS_project.pdf
   image: AEGISS_project.jpg
   authors: Peter Diggle
 - title: "A Randomised Double-blind Trial of Taurolidine-citrate Catheter Locks for the Prevention of Bacteraemia in Cuffed and Tunnelled Haemodialysis Catheters"
   file: double_blind_catheter.pdf
   image: double_blind_catheter.jpg
   authors: Peter Diggle
 - title: "Impulsivity Versus Apathy in Parkinson&#39;s Disease: a Comparison of Clinical, Psychiatric and Behavioural Correlates"
   file: impulsivity_vs_apathy.pdf
   image: impulsivity_vs_apathy.jpg
   authors: In&#234;s Sousa
 - title: "Effect of Social Deprivation on Weight in the UK Cystic Fibrosis Population"
   file: ECF_Weight_29May.pdf
   image: ECF_Weight_29May.jpg
   authors: Peter Diggle
 - title: "Development of &alpha;-synuclein as a Potential Molecular Marker for Parkinson&#39;s Disease"
   file: parkinson.pdf
   image: parkinson.jpg
   authors: Gerwyn Green, Peter Diggle
 - title: "Impact of Geostatistical Methods on Determining Boundaries of Hotspots of Malaria"
   file: HotspotMethods_PosterDraft.ppt
   image: HotspotMethods_PosterDraft.png
   authors: Emanuele Giorgi, Peter Diggle
 - title: "Cardiovascular Disease (CVD) Modelling Project"
   file: Kirk_LILAC_Poster_7_October_v2.ppt
   image: Kirk_LILAC_Poster_7_October_v2.png
   authors: Kirk Allen, Peter Diggle
 - title: "Spatio-temporal Changes in Childhood Malaria in Malawi"
   file: malaria_changes.pdf
   image: malaria_changes.png
   authors: Emanuele Giorgi, Peter Diggle
 - title: "Seasonal Influenza - A Simulation Model Based on a Social Network"
   file: lancet_seasonal_influenza.pdf
   image: lancet_seasonal_influenza.jpg
   authors: Rhiannon Edge, Tom Keegan, Barry Rowlingson
 - title: "Adaptive Geostatistical Design"
   file: MLW-MRC_Poster08Dec2014_MGC_PJD.pdf
   image: MLW-MRC_Poster08Dec2014_MGC_PJD.png
   authors: Peter Diggle
 - title: "One Health e-Surveillance for Early Detection of Gastrointestinal Disease Outbreaks"
   file: ISDS2015_poster_gi_early_detection.pdf
   image: ISDS2015_poster_gi_early_detection.png
   authors: Alison Hale, Barry Rowlingson, Emanuele Giorgio, Peter Diggle
 - title: "Bayesian Spatiotemporal Modelling of Survival Outcomes in Long-Term Studies"
   file: ziyu_july_2016.pdf
   image: ziyu_july_2016.png
   authors: Ziyu Zheng, Barry Rowlingson, Ben Taylor
 - title: Using Health Informatics to Improve Neurological Care
   file: Fran_20180405-Symposium_Poster.pdf
   image: Fran_20180405-Symposium_Poster.png
   authors: Fran Biggin
